/**
 * POST /api/sandboxes/:id/ai/execute
 * Executes SQL generated by AI for a given sandbox's AI log.
 * - Authenticates user
 * - Verifies sandbox ownership
 * - Validates input aiLogId (uuid)
 * - Fetches AI log for this sandbox and ensures not already executed
 * - Executes the AI-generated SQL using the sandbox credentials
 * - Marks ai_log.executed = true on success
 * - Returns execution results
 */

import { createFileRoute } from "@tanstack/react-router";
import { getCookie } from "@tanstack/react-start/server";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { db } from "#/db";
import { aiLogs, sandboxes } from "#/db/schema";
import { errorResponse, successResponse } from "#/lib/api-response";
import { executeQuery } from "#/lib/query-executor";
import { verifyToken } from "#/lib/session";

const SESSION_COOKIE_NAME = "session";

export const Route = createFileRoute("/api/sandboxes/$id/ai/execute")({
	server: {
		handlers: {
			POST: async ({ request, params }) => {
				const { id } = params;

				// Step 1: Authenticate user
				const token = getCookie(SESSION_COOKIE_NAME);
				if (!token) {
					return errorResponse(
						"AUTHENTICATION_REQUIRED",
						"Authentication required",
						401,
					);
				}

				const payload = await verifyToken(token);
				if (!payload) {
					return errorResponse(
						"INVALID_SESSION",
						"Invalid or expired session",
						401,
					);
				}

				const userId = payload.userId;

				// Step 2: Parse and validate request body
				let body: unknown;
				try {
					body = await request.json();
				} catch {
					return errorResponse("invalid_json_body", "Invalid JSON body", 400);
				}

				const schema = z.object({ aiLogId: z.string().uuid() });
				// Avoid using `any` for type-safety: cast to unknown instead
				const parsed = schema.safeParse((body ?? {}) as unknown);
				if (!parsed.success) {
					return errorResponse(
						"INVALID_AI_LOG_ID",
						"Invalid aiLogId. Must be a UUID",
						400,
					);
				}
				const { aiLogId } = parsed.data;

				// Step 3: Fetch sandbox and verify ownership
				const [sandbox] = await db
					.select()
					.from(sandboxes)
					.where(eq(sandboxes.id, id))
					.limit(1);

				if (!sandbox) {
					return errorResponse("sandbox_not_found", "Sandbox not found", 404);
				}

				if (sandbox.userId !== userId) {
					return errorResponse("access_denied", "Access denied", 403);
				}

				// Step 4: Fetch AI log for this sandbox
				const [aiLog] = await db
					.select()
					.from(aiLogs)
					.where(and(eq(aiLogs.id, aiLogId), eq(aiLogs.sandboxId, sandbox.id)))
					.limit(1);

				if (!aiLog) {
					return errorResponse(
						"AI_LOG_NOT_FOUND",
						"AI log not found for this sandbox",
						400,
					);
				}

				if (aiLog.executed) {
					return errorResponse(
						"AI_LOG_ALREADY_EXECUTED",
						"AI log already executed",
						400,
					);
				}

				const sql = aiLog.sqlGenerated;
				if (!sql) {
					return errorResponse(
						"NO_SQL_GENERATED",
						"No SQL generated for this AI log",
						400,
					);
				}

				// Step 5: Execute SQL using sandbox credentials
				try {
					const result = await executeQuery(
						{
							id: sandbox.id,
							dbName: sandbox.dbName,
							dbUser: sandbox.dbUser,
							dbPassword: sandbox.dbPassword,
							host: sandbox.host,
							port: sandbox.port,
							engine: sandbox.engine,
						},
						sql,
					);

					// Step 6: Mark AI log as executed on success
					if (result.success) {
						await db
							.update(aiLogs)
							.set({ executed: true })
							.where(eq(aiLogs.id, aiLog.id));
					}

					// Step 7: Return execution results
					return successResponse(
						{
							rows: result.rows,
							rowCount: result.rowCount,
							executionTimeMs: result.executionTimeMs,
							error: result.error,
						},
						200,
					);
				} catch (error) {
					console.error("[AI Execute] Unexpected error:", error);
					return errorResponse(
						"INTERNAL_SERVER_ERROR",
						"Internal server error during SQL execution",
						500,
					);
				}
			},
		},
	},
});
