/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ApiTemplatesIndexRouteImport } from './routes/api/templates/index'
import { Route as ApiSandboxesIndexRouteImport } from './routes/api/sandboxes/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as ApiSandboxesIdRouteImport } from './routes/api/sandboxes/$id'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as AppDashboardSettingsRouteImport } from './routes/_app/dashboard/settings'
import { Route as AppDashboardSandboxesRouteImport } from './routes/_app/dashboard/sandboxes'
import { Route as AppDashboardHelpRouteImport } from './routes/_app/dashboard/help'
import { Route as AppDashboardConsoleRouteImport } from './routes/_app/dashboard/console'
import { Route as AppDashboardAiSeederRouteImport } from './routes/_app/dashboard/ai-seeder'
import { Route as AppDashboardAccountRouteImport } from './routes/_app/dashboard/account'
import { Route as ApiSandboxesIdTablesRouteImport } from './routes/api/sandboxes/$id/tables'
import { Route as ApiSandboxesIdQueryRouteImport } from './routes/api/sandboxes/$id/query'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'
import { Route as ApiAuthGithubCallbackRouteImport } from './routes/api/auth/github/callback'
import { Route as AppDashboardSandboxesNewRouteImport } from './routes/_app/dashboard/sandboxes/new'
import { Route as AppDashboardSandboxesIdRouteImport } from './routes/_app/dashboard/sandboxes/$id'
import { Route as ApiSandboxesIdAiLogsRouteImport } from './routes/api/sandboxes/$id/ai/logs'
import { Route as ApiSandboxesIdAiGenerateRouteImport } from './routes/api/sandboxes/$id/ai/generate'
import { Route as ApiSandboxesIdAiExecuteRouteImport } from './routes/api/sandboxes/$id/ai/execute'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesIndexRoute = ApiTemplatesIndexRouteImport.update({
  id: '/api/templates/',
  path: '/api/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSandboxesIndexRoute = ApiSandboxesIndexRouteImport.update({
  id: '/api/sandboxes/',
  path: '/api/sandboxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const ApiSandboxesIdRoute = ApiSandboxesIdRouteImport.update({
  id: '/api/sandboxes/$id',
  path: '/api/sandboxes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardSandboxesRoute = AppDashboardSandboxesRouteImport.update({
  id: '/sandboxes',
  path: '/sandboxes',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardHelpRoute = AppDashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardConsoleRoute = AppDashboardConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardAiSeederRoute = AppDashboardAiSeederRouteImport.update({
  id: '/ai-seeder',
  path: '/ai-seeder',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardAccountRoute = AppDashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppDashboardRoute,
} as any)
const ApiSandboxesIdTablesRoute = ApiSandboxesIdTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => ApiSandboxesIdRoute,
} as any)
const ApiSandboxesIdQueryRoute = ApiSandboxesIdQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => ApiSandboxesIdRoute,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)
const ApiAuthGithubCallbackRoute = ApiAuthGithubCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGithubRoute,
} as any)
const AppDashboardSandboxesNewRoute =
  AppDashboardSandboxesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppDashboardSandboxesRoute,
  } as any)
const AppDashboardSandboxesIdRoute = AppDashboardSandboxesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDashboardSandboxesRoute,
} as any)
const ApiSandboxesIdAiLogsRoute = ApiSandboxesIdAiLogsRouteImport.update({
  id: '/ai/logs',
  path: '/ai/logs',
  getParentRoute: () => ApiSandboxesIdRoute,
} as any)
const ApiSandboxesIdAiGenerateRoute =
  ApiSandboxesIdAiGenerateRouteImport.update({
    id: '/ai/generate',
    path: '/ai/generate',
    getParentRoute: () => ApiSandboxesIdRoute,
  } as any)
const ApiSandboxesIdAiExecuteRoute = ApiSandboxesIdAiExecuteRouteImport.update({
  id: '/ai/execute',
  path: '/ai/execute',
  getParentRoute: () => ApiSandboxesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/dashboard/account': typeof AppDashboardAccountRoute
  '/dashboard/ai-seeder': typeof AppDashboardAiSeederRoute
  '/dashboard/console': typeof AppDashboardConsoleRoute
  '/dashboard/help': typeof AppDashboardHelpRoute
  '/dashboard/sandboxes': typeof AppDashboardSandboxesRouteWithChildren
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/sandboxes/$id': typeof ApiSandboxesIdRouteWithChildren
  '/dashboard/': typeof AppDashboardIndexRoute
  '/api/sandboxes/': typeof ApiSandboxesIndexRoute
  '/api/templates/': typeof ApiTemplatesIndexRoute
  '/dashboard/sandboxes/$id': typeof AppDashboardSandboxesIdRoute
  '/dashboard/sandboxes/new': typeof AppDashboardSandboxesNewRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/sandboxes/$id/query': typeof ApiSandboxesIdQueryRoute
  '/api/sandboxes/$id/tables': typeof ApiSandboxesIdTablesRoute
  '/api/sandboxes/$id/ai/execute': typeof ApiSandboxesIdAiExecuteRoute
  '/api/sandboxes/$id/ai/generate': typeof ApiSandboxesIdAiGenerateRoute
  '/api/sandboxes/$id/ai/logs': typeof ApiSandboxesIdAiLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/account': typeof AppDashboardAccountRoute
  '/dashboard/ai-seeder': typeof AppDashboardAiSeederRoute
  '/dashboard/console': typeof AppDashboardConsoleRoute
  '/dashboard/help': typeof AppDashboardHelpRoute
  '/dashboard/sandboxes': typeof AppDashboardSandboxesRouteWithChildren
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/sandboxes/$id': typeof ApiSandboxesIdRouteWithChildren
  '/dashboard': typeof AppDashboardIndexRoute
  '/api/sandboxes': typeof ApiSandboxesIndexRoute
  '/api/templates': typeof ApiTemplatesIndexRoute
  '/dashboard/sandboxes/$id': typeof AppDashboardSandboxesIdRoute
  '/dashboard/sandboxes/new': typeof AppDashboardSandboxesNewRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/sandboxes/$id/query': typeof ApiSandboxesIdQueryRoute
  '/api/sandboxes/$id/tables': typeof ApiSandboxesIdTablesRoute
  '/api/sandboxes/$id/ai/execute': typeof ApiSandboxesIdAiExecuteRoute
  '/api/sandboxes/$id/ai/generate': typeof ApiSandboxesIdAiGenerateRoute
  '/api/sandboxes/$id/ai/logs': typeof ApiSandboxesIdAiLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/_app/dashboard/account': typeof AppDashboardAccountRoute
  '/_app/dashboard/ai-seeder': typeof AppDashboardAiSeederRoute
  '/_app/dashboard/console': typeof AppDashboardConsoleRoute
  '/_app/dashboard/help': typeof AppDashboardHelpRoute
  '/_app/dashboard/sandboxes': typeof AppDashboardSandboxesRouteWithChildren
  '/_app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/api/auth/github': typeof ApiAuthGithubRouteWithChildren
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/sandboxes/$id': typeof ApiSandboxesIdRouteWithChildren
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/api/sandboxes/': typeof ApiSandboxesIndexRoute
  '/api/templates/': typeof ApiTemplatesIndexRoute
  '/_app/dashboard/sandboxes/$id': typeof AppDashboardSandboxesIdRoute
  '/_app/dashboard/sandboxes/new': typeof AppDashboardSandboxesNewRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/sandboxes/$id/query': typeof ApiSandboxesIdQueryRoute
  '/api/sandboxes/$id/tables': typeof ApiSandboxesIdTablesRoute
  '/api/sandboxes/$id/ai/execute': typeof ApiSandboxesIdAiExecuteRoute
  '/api/sandboxes/$id/ai/generate': typeof ApiSandboxesIdAiGenerateRoute
  '/api/sandboxes/$id/ai/logs': typeof ApiSandboxesIdAiLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/api/health'
    | '/dashboard/account'
    | '/dashboard/ai-seeder'
    | '/dashboard/console'
    | '/dashboard/help'
    | '/dashboard/sandboxes'
    | '/dashboard/settings'
    | '/api/auth/github'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/sandboxes/$id'
    | '/dashboard/'
    | '/api/sandboxes/'
    | '/api/templates/'
    | '/dashboard/sandboxes/$id'
    | '/dashboard/sandboxes/new'
    | '/api/auth/github/callback'
    | '/api/auth/google/callback'
    | '/api/sandboxes/$id/query'
    | '/api/sandboxes/$id/tables'
    | '/api/sandboxes/$id/ai/execute'
    | '/api/sandboxes/$id/ai/generate'
    | '/api/sandboxes/$id/ai/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/api/health'
    | '/dashboard/account'
    | '/dashboard/ai-seeder'
    | '/dashboard/console'
    | '/dashboard/help'
    | '/dashboard/sandboxes'
    | '/dashboard/settings'
    | '/api/auth/github'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/sandboxes/$id'
    | '/dashboard'
    | '/api/sandboxes'
    | '/api/templates'
    | '/dashboard/sandboxes/$id'
    | '/dashboard/sandboxes/new'
    | '/api/auth/github/callback'
    | '/api/auth/google/callback'
    | '/api/sandboxes/$id/query'
    | '/api/sandboxes/$id/tables'
    | '/api/sandboxes/$id/ai/execute'
    | '/api/sandboxes/$id/ai/generate'
    | '/api/sandboxes/$id/ai/logs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/privacy'
    | '/terms'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_app/dashboard'
    | '/api/health'
    | '/_app/dashboard/account'
    | '/_app/dashboard/ai-seeder'
    | '/_app/dashboard/console'
    | '/_app/dashboard/help'
    | '/_app/dashboard/sandboxes'
    | '/_app/dashboard/settings'
    | '/api/auth/github'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/sandboxes/$id'
    | '/_app/dashboard/'
    | '/api/sandboxes/'
    | '/api/templates/'
    | '/_app/dashboard/sandboxes/$id'
    | '/_app/dashboard/sandboxes/new'
    | '/api/auth/github/callback'
    | '/api/auth/google/callback'
    | '/api/sandboxes/$id/query'
    | '/api/sandboxes/$id/tables'
    | '/api/sandboxes/$id/ai/execute'
    | '/api/sandboxes/$id/ai/generate'
    | '/api/sandboxes/$id/ai/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRouteWithChildren
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiSandboxesIdRoute: typeof ApiSandboxesIdRouteWithChildren
  ApiSandboxesIndexRoute: typeof ApiSandboxesIndexRoute
  ApiTemplatesIndexRoute: typeof ApiTemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/': {
      id: '/api/templates/'
      path: '/api/templates'
      fullPath: '/api/templates/'
      preLoaderRoute: typeof ApiTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sandboxes/': {
      id: '/api/sandboxes/'
      path: '/api/sandboxes'
      fullPath: '/api/sandboxes/'
      preLoaderRoute: typeof ApiSandboxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/api/sandboxes/$id': {
      id: '/api/sandboxes/$id'
      path: '/api/sandboxes/$id'
      fullPath: '/api/sandboxes/$id'
      preLoaderRoute: typeof ApiSandboxesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/settings': {
      id: '/_app/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/sandboxes': {
      id: '/_app/dashboard/sandboxes'
      path: '/sandboxes'
      fullPath: '/dashboard/sandboxes'
      preLoaderRoute: typeof AppDashboardSandboxesRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/help': {
      id: '/_app/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof AppDashboardHelpRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/console': {
      id: '/_app/dashboard/console'
      path: '/console'
      fullPath: '/dashboard/console'
      preLoaderRoute: typeof AppDashboardConsoleRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/ai-seeder': {
      id: '/_app/dashboard/ai-seeder'
      path: '/ai-seeder'
      fullPath: '/dashboard/ai-seeder'
      preLoaderRoute: typeof AppDashboardAiSeederRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/account': {
      id: '/_app/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof AppDashboardAccountRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/api/sandboxes/$id/tables': {
      id: '/api/sandboxes/$id/tables'
      path: '/tables'
      fullPath: '/api/sandboxes/$id/tables'
      preLoaderRoute: typeof ApiSandboxesIdTablesRouteImport
      parentRoute: typeof ApiSandboxesIdRoute
    }
    '/api/sandboxes/$id/query': {
      id: '/api/sandboxes/$id/query'
      path: '/query'
      fullPath: '/api/sandboxes/$id/query'
      preLoaderRoute: typeof ApiSandboxesIdQueryRouteImport
      parentRoute: typeof ApiSandboxesIdRoute
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
    '/api/auth/github/callback': {
      id: '/api/auth/github/callback'
      path: '/callback'
      fullPath: '/api/auth/github/callback'
      preLoaderRoute: typeof ApiAuthGithubCallbackRouteImport
      parentRoute: typeof ApiAuthGithubRoute
    }
    '/_app/dashboard/sandboxes/new': {
      id: '/_app/dashboard/sandboxes/new'
      path: '/new'
      fullPath: '/dashboard/sandboxes/new'
      preLoaderRoute: typeof AppDashboardSandboxesNewRouteImport
      parentRoute: typeof AppDashboardSandboxesRoute
    }
    '/_app/dashboard/sandboxes/$id': {
      id: '/_app/dashboard/sandboxes/$id'
      path: '/$id'
      fullPath: '/dashboard/sandboxes/$id'
      preLoaderRoute: typeof AppDashboardSandboxesIdRouteImport
      parentRoute: typeof AppDashboardSandboxesRoute
    }
    '/api/sandboxes/$id/ai/logs': {
      id: '/api/sandboxes/$id/ai/logs'
      path: '/ai/logs'
      fullPath: '/api/sandboxes/$id/ai/logs'
      preLoaderRoute: typeof ApiSandboxesIdAiLogsRouteImport
      parentRoute: typeof ApiSandboxesIdRoute
    }
    '/api/sandboxes/$id/ai/generate': {
      id: '/api/sandboxes/$id/ai/generate'
      path: '/ai/generate'
      fullPath: '/api/sandboxes/$id/ai/generate'
      preLoaderRoute: typeof ApiSandboxesIdAiGenerateRouteImport
      parentRoute: typeof ApiSandboxesIdRoute
    }
    '/api/sandboxes/$id/ai/execute': {
      id: '/api/sandboxes/$id/ai/execute'
      path: '/ai/execute'
      fullPath: '/api/sandboxes/$id/ai/execute'
      preLoaderRoute: typeof ApiSandboxesIdAiExecuteRouteImport
      parentRoute: typeof ApiSandboxesIdRoute
    }
  }
}

interface AppDashboardSandboxesRouteChildren {
  AppDashboardSandboxesIdRoute: typeof AppDashboardSandboxesIdRoute
  AppDashboardSandboxesNewRoute: typeof AppDashboardSandboxesNewRoute
}

const AppDashboardSandboxesRouteChildren: AppDashboardSandboxesRouteChildren = {
  AppDashboardSandboxesIdRoute: AppDashboardSandboxesIdRoute,
  AppDashboardSandboxesNewRoute: AppDashboardSandboxesNewRoute,
}

const AppDashboardSandboxesRouteWithChildren =
  AppDashboardSandboxesRoute._addFileChildren(
    AppDashboardSandboxesRouteChildren,
  )

interface AppDashboardRouteChildren {
  AppDashboardAccountRoute: typeof AppDashboardAccountRoute
  AppDashboardAiSeederRoute: typeof AppDashboardAiSeederRoute
  AppDashboardConsoleRoute: typeof AppDashboardConsoleRoute
  AppDashboardHelpRoute: typeof AppDashboardHelpRoute
  AppDashboardSandboxesRoute: typeof AppDashboardSandboxesRouteWithChildren
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardAccountRoute: AppDashboardAccountRoute,
  AppDashboardAiSeederRoute: AppDashboardAiSeederRoute,
  AppDashboardConsoleRoute: AppDashboardConsoleRoute,
  AppDashboardHelpRoute: AppDashboardHelpRoute,
  AppDashboardSandboxesRoute: AppDashboardSandboxesRouteWithChildren,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiAuthGithubRouteChildren {
  ApiAuthGithubCallbackRoute: typeof ApiAuthGithubCallbackRoute
}

const ApiAuthGithubRouteChildren: ApiAuthGithubRouteChildren = {
  ApiAuthGithubCallbackRoute: ApiAuthGithubCallbackRoute,
}

const ApiAuthGithubRouteWithChildren = ApiAuthGithubRoute._addFileChildren(
  ApiAuthGithubRouteChildren,
)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

interface ApiSandboxesIdRouteChildren {
  ApiSandboxesIdQueryRoute: typeof ApiSandboxesIdQueryRoute
  ApiSandboxesIdTablesRoute: typeof ApiSandboxesIdTablesRoute
  ApiSandboxesIdAiExecuteRoute: typeof ApiSandboxesIdAiExecuteRoute
  ApiSandboxesIdAiGenerateRoute: typeof ApiSandboxesIdAiGenerateRoute
  ApiSandboxesIdAiLogsRoute: typeof ApiSandboxesIdAiLogsRoute
}

const ApiSandboxesIdRouteChildren: ApiSandboxesIdRouteChildren = {
  ApiSandboxesIdQueryRoute: ApiSandboxesIdQueryRoute,
  ApiSandboxesIdTablesRoute: ApiSandboxesIdTablesRoute,
  ApiSandboxesIdAiExecuteRoute: ApiSandboxesIdAiExecuteRoute,
  ApiSandboxesIdAiGenerateRoute: ApiSandboxesIdAiGenerateRoute,
  ApiSandboxesIdAiLogsRoute: ApiSandboxesIdAiLogsRoute,
}

const ApiSandboxesIdRouteWithChildren = ApiSandboxesIdRoute._addFileChildren(
  ApiSandboxesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthGithubRoute: ApiAuthGithubRouteWithChildren,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiSandboxesIdRoute: ApiSandboxesIdRouteWithChildren,
  ApiSandboxesIndexRoute: ApiSandboxesIndexRoute,
  ApiTemplatesIndexRoute: ApiTemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
